# Generated by Django 4.2.6 on 2023-12-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DNS',
            field=models.DateField(default='2004-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='NSS',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pathologies_chroniques',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sous_trait_medi_part',
            field=models.CharField(default='', max_length=350),
        ),
    ]
