# Generated by Django 4.2.6 on 2023-12-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dns_customuser_nss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pathologies_chroniques',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sous_trait_medi_part',
            field=models.TextField(default=''),
        ),
    ]
