# Generated by Django 4.2.6 on 2024-01-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_pathologies_chroniques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='NSS',
            field=models.CharField(blank=True, default='1234567891012', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
    ]
