# Generated by Django 4.2.6 on 2024-01-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_dns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DNS',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pathologies_chroniques',
            field=models.TextField(default='Non'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sous_trait_medi_part',
            field=models.TextField(default='Non'),
        ),
    ]
