# Generated by Django 4.2.6 on 2023-12-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_consultation_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='Type',
            field=models.CharField(default='medicale', max_length=50),
        ),
    ]
