# Generated by Django 4.2.6 on 2024-01-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_consultation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='Type',
            field=models.CharField(choices=[('MED', 'medicale'), ('PAR', 'paramedicale')], max_length=3),
        ),
    ]
