# Generated by Django 4.2.6 on 2024-01-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_consultation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='user',
            new_name='User',
        ),
    ]
